2.7: Changes to Auto-configuration #156
spring-projects-experimental/spring-boot-migrator pull request #182
Opened 2022-06-30 12:22 UTC by ijusti

2022-06-30 12:22 UTC, pivotal-cla commented
@ijusti Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-boot-migrator&pullRequestId=182)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects-experimental/spring-boot-migrator&pullRequestId=182) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-07-07 09:14 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/impl/OpenRewriteMavenBuildFile.java
> +                    .filter(not(d -> d.getExclusions().isEmpty()))
TIL

2022-07-07 12:48 UTC, fabapp2 commented
Hi @ijusti! 
I've been on PTO thus the long delay.
Thanks a lot for your contribution and the many beautifications and fixes. Very much appreciated! 🙏 
I had a few comments regarding the operation on files and would ask you to provide at least a test for the `Action` itself.
If you could resolve these comments I'll happily merge your PR.
Thanks again!

2022-07-07 13:43 UTC, fabapp2 requested changes

2022-07-07 13:43 UTC, fabapp2 commented on components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-autoconfiguration-update.yaml
> +    type: org.springframework.sbm.common.migration.conditions.TrueCondition
The condition for the recipe should better be `IsMatchingSpringBootVersion` with pattern `2.7.` so it is only shown for 2.7 Boot applications.

2022-07-08 11:36 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/como/conditions/BootHasAutoconfigurationCondition.java
> +    public boolean evaluate(ProjectContext context) {
i need to check that near spring.factories no new file exists

2022-07-11 11:41 UTC, fabapp2 requested changes

2022-07-11 12:51 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java
> +    public void apply(ProjectContext context) {
this search does not work. there is no spring.factories in ProjectContext. That is why I worked directly with files

2022-07-12 08:48 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/como/conditions/BootHasAutoconfigurationCondition.java
> +    public boolean evaluate(ProjectContext context) {
this good, and I tried to make this way? but there is no spring.factories in context

2022-07-12 08:50 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java
> +    public void apply(ProjectContext context) {
Also I guess parser should also understand new file 
`**/src/main/resources/META-INF/org.springframework.boot.autoconfigure.AutoConfiguration.imports`

2022-07-12 08:53 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/como/conditions/BootHasAutoconfigurationCondition.java
> +    public boolean evaluate(ProjectContext context) {
something like this, that mean that there is no new imports near spring.factories

```
return context.search(new PathPatternMatchingProjectResourceFinder("**/src/main/resources/META-INF/spring.factories"))
.stream()
.anyMatch(resource-> context.search(new PathPatternMatchingProjectResourceFinder("resource.path.parent +"org.springframework.boot.autoconfigure.AutoConfiguration.imports")).isEmpty())
```

2022-07-12 11:08 UTC, fabapp2 commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java
> +    public void apply(ProjectContext context) {
The parser is fixed now (PR #191) and yes, the new resource should be parsed by the parser.

2022-07-12 11:48 UTC, fabapp2 commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/como/conditions/BootHasAutoconfigurationCondition.java
> +    public boolean evaluate(ProjectContext context) {
Ah, I got your valid point here.
I am thinking that if we replace all old with new factories in one go and remove the old ones (or move with `MoveFilesAction`), there should not be both (old and new) in one project. If this is "guaranteed" we can skip the second part of the check?

You could replace `resource.path.parent` with `resource.getAbsoluetPath().getParent().resolve("org.springframework.boot.autoconfigure.AutoConfiguration.imports")` and then use `AbsolutePathResourceFinder` with this path.

2022-07-14 16:28 UTC, fabapp2 commented
Hi @ijusti !
Could you provide the requested changes?
I am sorry if I am pushy here but we'll need this issue (very) soon.
It's no problem if you don't have time, I'd merge what you did and add the requested changes myself then (crediting you as author). 
Let me know what works for you?

2022-07-21 10:17 UTC, ijusti commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java
> +    public void apply(ProjectContext context) {
after rebase scan command always has **projectRoot="."**
<img width="814" alt="image" src="https://user-images.githubusercontent.com/5530459/180190648-69666051-3da4-42d4-93b9-962de8bd2368.png">

2022-07-21 12:49 UTC, fabapp2 commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java
> +    public void apply(ProjectContext context) {
Hi @ijusti !
You're right with the recent update to spring-shell `2.1.0-RC1` the command property resolution changed.
You'd either need to add `arity=1` or provide the name of the property like so `scan --projectRoot=...`.
As we need this change today, my colleagues will finish it. I will merge back what you provided so far and they'll add the test, condition, and refactored action. We will mention you as a contributor though.

2022-07-21 12:49 UTC, merged