Fix integration test
spring-projects-experimental/spring-boot-migrator pull request #235
Opened 2022-07-17 17:59 UTC by cab105

The IntegrationTestBaseClass is looking for the `MAVEN_HOME` environment variable, which only applies for Maven 1.x instead of `M2_HOME` which applies to Maven 2.x. This PR adds support for the second environment variable.

2022-07-17 20:30 UTC, cab105 commented
This PR includes an additional fix to ensure the version of spring-boot-starter-parent exists in Maven Central (3.x doesn't according to https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent)

2022-07-18 09:17 UTC, fabapp2 requested changes

2022-07-18 09:17 UTC, fabapp2 commented on applications/spring-shell/src/test/java/org/springframework/sbm/IntegrationTestBaseClass.java
> +            mvnHome = System.getenv("M2_HOME");
👍

2022-07-18 09:17 UTC, fabapp2 commented on components/sbm-openrewrite/src/test/java/org/springframework/sbm/openrewrite/maven/BumpParentVersionTest.java
> +        List<Result> results = new UpgradeParentVersion("org.springframework.boot", "spring-boot-starter-parent", "2.7.1", null).run(parsedPom);
The test was correct. Now it's setting the version of the parent pom to the version it already has and the `UpgradeParentPom` recipe will do nothing.
The issue (before upgrading OpenRewrite to a more recent version as on `main` now) was that the change to `3.0.0-M3` was applied in the `pom.xml` source (given that the milestone repo was configured)  but not reflected in the pom's model. 
This is the case now in `main` and the test proved that in latest OR version the change is reflected in the model too.
The comment should be removed as the call to `RefreshPomModel` in `OpenRewriteMavenBuildFile.upgradeParentVersion()` has been removed.

2022-07-18 16:38 UTC, fabapp2 requested changes

2022-07-18 16:38 UTC, fabapp2 commented on components/sbm-openrewrite/src/test/java/org/springframework/sbm/openrewrite/maven/BumpParentVersionTest.java
> +        List<Result> results = new UpgradeParentVersion("org.springframework.boot", "spring-boot-starter-parent", "2.7.1", null).run(parsedPom);
Hm. Sounds like the root problem was that Rewrite couldn't retrieve the parent in `3.0.0-M3` from the configured milestone repo?
Actually, the test could be deleted. I'd say. 😬 
After removing the call to `RefreshPomModel` in `OpenRewriteMavenBuildFile.upgradeParentVersion()` after upgrading rewrite to  `7.26.0` changes to the parent version are reflected in the underlying model by rewrite automatically. The intention of the test was to remind us about this fact.

2022-07-18 16:51 UTC, cab105 commented
That's my take. Okay let me take it out and verify.

2022-07-30 20:18 UTC, fabapp2 approved these changes

2022-07-30 20:19 UTC, merged