#159 Added action for Johnzon upgrade for Spring boot migration 2.7 t…
spring-projects-experimental/spring-boot-migrator pull request #265
Opened 2022-07-27 12:56 UTC by ravig-kant

…o 3.x

2022-07-28 17:02 UTC, fabapp2 requested changes
Hi @ravig-kant 
thanks a lot for you contribution, very much appreciated!
I had a few small comments, could you have a look?
Looking forward to merge your PR.

2022-07-28 18:48 UTC, BoykoAlex commented
Shouldn't the recipe go in **spring-boot-upgrade-30** project under the root? Or at lease some Rewrite dependent portion of the SBM recipe?

2022-07-29 04:43 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/conditions/JohnzonDependencyCondition.java
> +        return context.getProjectJavaSources()
I think I have to consider both conditions. It's possible that dependency is spring managed and hence doesn't reflect in pom. However, the project is nonetheless using Johnzon classes.

2022-07-29 07:13 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/actions/Boot_27_30_UpgradeReplaceJohnzonDependenciesTest.java
> +    private static final String JHONZON_UNSUPPORTED_DEPENDENCY = "org.apache.johnzon:johnzon-core:1.2.11";
Thanks. Code updated.

2022-07-29 07:14 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/actions/Boot_27_30_UpgradeReplaceJohnzonDependencies.java
> +        buildFile.removeDependenciesMatchingRegex(JHONZON_DEPENDENCY_PATTERN);
Thanks. Code updated.

2022-07-29 07:14 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/actions/Boot_27_30_UpgradeReplaceJohnzonDependenciesTest.java
> +        assertTrue(projectContext
Thanks. Code updated.

2022-07-29 07:14 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/actions/Boot_27_30_UpgradeReplaceJohnzonDependenciesTest.java
> +                .addRegistrar(new SpringBootApplicationPropertiesRegistrar(new SpringApplicationPropertiesPathMatcher()))
Thanks. Code updated.

2022-07-29 07:17 UTC, ravig-kant commented
Hi @fabapp2 

I have a question about handling Johnzon dependencies for multi-module projects. In such cases should we not be updating the parent projects dependency management section? Also for spring-managed cases, we will have to add a dependency to the child module.

> Hi @ravig-kant thanks a lot for you contribution, very much appreciated! I had a few small comments, could you have a look? Looking forward to merge your PR.

Thanks
Ravi

2022-07-30 22:23 UTC, fabapp2 commented
> Shouldn't the recipe go in **spring-boot-upgrade-30** project under the root? Or at lease some Rewrite dependent portion of the SBM recipe?

I'd say it's the right module for now. @sanagaraj-pivotal killed the `spring-boot-upgrade-30´ module as this is basically `sbm-openrewrite` where the resources were moved to. As the migration is done in plain SBM for now this module is ok imho.

2022-08-01 07:44 UTC, fabapp2 commented
> Hi @fabapp2
> 
> I have a question about handling Johnzon dependencies for multi-module projects. In such cases should we not be updating the parent projects dependency management section? Also for spring-managed cases, we will have to add a dependency to the child module.
> 
> > Hi @ravig-kant thanks a lot for you contribution, very much appreciated! I had a few small comments, could you have a look? Looking forward to merge your PR.
> 
> Thanks Ravi

Hi @ravig-kant 

I am currently working on multi-module support.
Moving fixed set versions into a `dependencyManagement` section is something I could see as a separate recipe.
For this issue it should be enough to just set the version and classifier for all johnson dependencies found.

Making this multi-module aware could be achieved like so:
```
context.getApplicationModules().stream()
                .map(ApplicationModule::getBuildFile)
                .filter(b -> b.hasDeclaredDependencyMatchingRegex("..."))
                .forEach(this::doSomethingWithBuildFileContainingJohnzonDependency);
```

2022-08-02 09:09 UTC, fabapp2 commented
Hi @ravig-kant,
only a few tweaks are required to merge your PR to `main`:

- [ ] Remove the checks for imports, just having the dependency without a version (managed by Boot) should trigger the replacement with 
```
<dependency>
            <groupId>org.apache.johnzon</groupId>
            <artifactId>johnzon-core</artifactId>
            <version>1.2.18</version>
	    <classifier>jakarta</classifier>
        </dependency>
```

- [ ] Add support for classifier in `Dependency.fromCoordinates()`
- [ ] Making the Action multi module aware by checking all `ApplicationModule`s
- [ ] Adjust the test to expect `jakarta` as classifier in the added dependency

2022-08-03 07:48 UTC, fabapp2 approved these changes

2022-08-03 07:51 UTC, fabapp2 commented
Thanks, @ravig-kant for your contribution 🎉

2022-08-03 08:00 UTC, ravig-kant commented on components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/actions/Boot_27_30_UpgradeReplaceJohnzonDependenciesTest.java
> +            "            <version>1.2.18-jakarta</version>\n" +
I think your comments and my next upload crossed. I added the test for the new case. Thanks for the review. Hopefully, I will improve and churn out better quality next time. I will pick up #225 now.

2022-08-03 08:01 UTC, merged