Add Mule package type to getTopmostApplicationModules
spring-projects-experimental/spring-boot-migrator pull request #385
Opened 2022-09-06 18:19 UTC by cab105

Following up on https://github.com/spring-projects-experimental/spring-boot-migrator/pull/373, I was able to figure out why my Mule project was not being picked up by Spring Boot Migrator.  Turns out there's a check in the dependent call of `getTopmostApplicationModules` that whitelists only `jar` based applications. However, Mulesoft projects built with Anypoint Studio defaults to using `mule-application`.  Since this is the package type that I've been using for my mule migration projects, the code has consistently failed.

This PR will whitelist this application type as the `migrate-mule-to-boot` recipe will convert the application type to `jar` after it runs.

2022-09-07 09:33 UTC, fabapp2 commented
Thank you @cab105 ! 🚀 
I had one comment.

2022-09-07 15:43 UTC, cab105 commented
> 

Dare I ask what the one comment is?

2022-09-18 22:25 UTC, fabapp2 requested changes

2022-09-18 22:30 UTC, fabapp2 approved these changes

2022-09-18 22:37 UTC, fabapp2 commented
> > 
> 
> Dare I ask what the one comment is?

Sorry, my bad. 🙈

2022-09-18 22:37 UTC, merged