Remove standard maven-compiler plugin for applications with boot parent - #428
spring-projects-experimental/spring-boot-migrator pull request #508
Opened 2022-10-27 16:28 UTC by ahmedmq

Changes for #428 

- Two Actions (`RemoveRedundantMavenCompilerPluginProperties`, `RemoveRedundantMavenCompilerPlugin`)
- New Recipe (`remove-redundant-maven-compiler-plugin.yaml`) and condition (`SpringBootMavenCompilerExists`)

2022-11-08 00:31 UTC, fabapp2 requested changes
Hi @ahmedmq 
I didn't make it through (5/23) but will proceed asap. 
I think by moving more logic into `Plugin` and `Plugin#Configuration` some parts will get shorter and more cohesive 🤞 

Thanks for your work! 🚀

2022-11-08 00:31 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/impl/OpenRewriteMavenBuildFile.java
> +				if (configurationTag.isPresent() && configurationTag.get().getChildren().size() > 0){
What about you replacin `.size() > 0` with `!...isEmpty()` ?

2022-11-08 00:31 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/impl/OpenRewriteMavenBuildFile.java
> +						String configurationXml = configurationTag.get().print(new XmlPrinter<>());
Any reason not using `configurationTag.get().getValue()` instead of `print(new XmlPrinter())` here?

2022-11-08 00:31 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/migration/actions/SetProperty.java
>  public class SetProperty extends AbstractAction {
Would `SetBuildFileProperty` be maybe a more cohesive name, especially in recipes?

2022-11-08 00:31 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/migration/recipe/AddMavenPlugin.java
> +				String configurationXml = MavenXmlMapper.writeMapper().writerWithDefaultPrettyPrinter()
interesting approach :)

2022-11-08 00:31 UTC, fabapp2 commented on components/sbm-core/src/main/java/org/springframework/sbm/build/migration/recipe/AddMavenPlugin.java
>  		sb.append("</artifactId>\n");
Not your code, but what about moving the rendering `createPluginTagString` into `Plugin`?
E.g. `plugin.render()`

2022-12-06 11:35 UTC, ahmedmq commented
@fabapp2 - Do you want to have a look at the changes done?

2022-12-15 10:53 UTC, fabapp2 approved these changes
Thanks @ahmedmq for your heroic effort with this contribution! 🚀

2022-12-15 10:56 UTC, merged