Improve `RemoveAnnotationVisitor` to remove unused types from annotation parameters
spring-projects-experimental/spring-boot-migrator pull request #980
Opened 2023-10-19 21:20 UTC by ammachado

2023-10-20 02:32 UTC, ammachado commented
I also submitted a PR to fix OpenRewrite: https://github.com/openrewrite/rewrite/pull/3638

2023-10-30 15:20 UTC, fabapp2 requested changes
Thank you for this contribution @ammachado 🚀 

I was looking at the tests but couldn't see any tests that proves that the change in `RemoveAnnotationVisitor` is required.
Could you provide a test that proves your change?
Thank you for improving the quality of the code. 
I hope you keep contributing. Could you provide future cleanups in a separate PR (or at least commit), that makes it easier to follow and understand the changes. 
(I know I am not a role model here) ;)

2023-10-30 15:20 UTC, fabapp2 commented on components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/java/RemoveAnnotationVisitorTest.java
> +                   \s
Can you also remove these `\s`s, please?

2023-10-30 15:20 UTC, fabapp2 commented on components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/java/RemoveAnnotationVisitorTest.java
> +        assertThat(result.print()).isEqualToNormalizingNewlines(expected);
Please reset this after removing `\s`.

2023-10-30 15:20 UTC, fabapp2 commented on components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/java/RemoveAnnotationVisitorTest.java
> +
Now that this is getting cleaned up a bit, could you remove the blank line too?

2026-05-12 20:38 UTC, closed without merging